[deploy]
bucket = 'sks-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'Sksanth/aws-bootcamp-cruddur-2023-'
ArtifactBucketName = "sks-codepipeline-cruddur-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'